# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: E-pharmacy Backend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of e-pharmacy app
tags:
  - name: E-pharmacy
    description: Operations about products.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /customers/{id}:
    get:
      $ref: ../swagger/paths/customers/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
